import { createContext, useContext, useState } from "react";

const StateContext = createContext({
    currentUser: {},
    userToken: null,
    setCurrentUser: () => {},
    setUserToken: () => {}
})

const propertiesJson = [
    {
        "id": 1,
        "title": "Qui molestiae voluptatem et sequi corrupti quae est.",
        "description": "Expedita quisquam non ut ut iusto voluptatibus. At repudiandae animi iusto similique. Facere facilis eos deserunt ut.",
        "price": "54132.49",
        "bedrooms": 5,
        "bathrooms": 1,
        "area": 3567,
        "location": "Buenos Aires",
        "phoneNumber": "+1.531.953.1432",
        "propertyType": "House",
        "propertyAddress": "22653 Maybell Springs Apt. 413\nKovacekland, ME 00217-7184",
        "propertyDescription": "Aut quae modi qui suscipit eaque repellat quo. Iste asperiores sit ducimus eum dolor velit. Cum non et vero quia consequatur aliquam quas.",
        "rentalPrice": null,
        "leaseTerm": "24 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "848.15",
        "rentalAgreement": "Eum praesentium vel sapiente similique aspernatur deserunt dolores deserunt. Occaecati nostrum cumque cupiditate magnam sint consequatur.",
        "preferredTenantProfile": "Illo quo odio necessitatibus qui est distinctio necessitatibus. Distinctio nam minus odit omnis unde. Nam nobis quo error voluptatem. Iure incidunt quasi nulla qui est sunt voluptatem.",
        "additionalNote": "Qui sed molestias cupiditate omnis dolor saepe aliquid eos. Nihil molestiae qui non eos quo.",
        "owner": {
            "id": 1,
            "given_name": "Astrid",
            "family_name": "Conn",
            "email": "emmanuelle.vonrueden@example.org",
            "email_verified_at": "2023-09-13T00:51:02.000000Z",
            "role": "owner",
            "telephone": "+1-208-507-6403",
            "country_id": 2,
            "city": "Los Angeles",
            "street": null,
            "number": "20",
            "appartment": "94162624",
            "zip_code": "3475",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:02.000000Z",
            "updated_at": "2023-09-13T00:51:02.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    },
    {
        "id": 2,
        "title": "Error amet eum accusamus culpa eligendi aliquam.",
        "description": "Ea pariatur sunt numquam consequuntur et. Molestiae vel illum pariatur. Iste molestiae consequuntur at maiores. Velit quod laborum vero repudiandae dolore asperiores omnis.",
        "price": "42949.02",
        "bedrooms": 5,
        "bathrooms": 1,
        "area": 3455,
        "location": "New York",
        "phoneNumber": "1-206-631-4338",
        "propertyType": "Condo",
        "propertyAddress": "9980 Hermiston Cliffs\nSummerport, OH 47729",
        "propertyDescription": "Repudiandae sint tenetur dolorem suscipit perferendis voluptates. Impedit optio sapiente numquam eaque. Et consectetur est cupiditate vitae commodi numquam. Consequuntur temporibus perferendis omnis provident non.",
        "rentalPrice": null,
        "leaseTerm": "6 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "356.04",
        "rentalAgreement": "Et consequatur et excepturi. Quaerat neque repellendus incidunt incidunt.",
        "preferredTenantProfile": "Quam et aperiam sed mollitia ut. Molestiae aut laudantium rerum enim. Reprehenderit omnis quia numquam ut sed eius.",
        "additionalNote": "Eius cumque sed accusantium ipsam officia. Rerum sit autem harum veritatis veritatis aut. Animi omnis repellendus voluptatibus incidunt voluptates totam eveniet. Expedita impedit praesentium cupiditate aut quaerat ad.",
        "owner": {
            "id": 3,
            "given_name": "Freddie",
            "family_name": "Labadie",
            "email": "okeefe.jovanny@example.net",
            "email_verified_at": "2023-09-13T00:51:02.000000Z",
            "role": "owner",
            "telephone": "(539) 642-7764",
            "country_id": 4,
            "city": "Boston",
            "street": null,
            "number": "249",
            "appartment": "21",
            "zip_code": "7674",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:02.000000Z",
            "updated_at": "2023-09-13T00:51:02.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    },
    {
        "id": 3,
        "title": "Neque possimus placeat id est odio cumque.",
        "description": "Vitae temporibus tenetur dicta dignissimos a dolor perferendis necessitatibus. Non officiis sed labore voluptatem. Occaecati quisquam in sit et sint esse a asperiores.",
        "price": "28487.35",
        "bedrooms": 4,
        "bathrooms": 1,
        "area": 3753,
        "location": "Lima",
        "phoneNumber": "(781) 615-3853",
        "propertyType": "Apartment",
        "propertyAddress": "214 Jeremy Dam Apt. 893\nNew Vito, IN 45349-3725",
        "propertyDescription": "Qui qui et doloremque vel velit enim dolores non. Odio et placeat molestiae quidem aut earum dolores sed. Aut et et quia et quod voluptatem. Quam necessitatibus aut voluptas enim voluptatum eligendi quae.",
        "rentalPrice": null,
        "leaseTerm": "24 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "478.45",
        "rentalAgreement": "Repudiandae animi rerum est sed inventore dolore. Nisi dicta ad voluptatibus quisquam asperiores. Repellendus quos inventore ea aspernatur facilis et quis. Eos molestiae error et omnis.",
        "preferredTenantProfile": "Cupiditate enim cum minus voluptatem. Esse quis quos earum libero et. Quisquam similique hic officiis eos. Rerum error optio ex qui.",
        "additionalNote": "Nam rerum enim excepturi sequi. Maxime iusto quod soluta maxime.",
        "owner": {
            "id": 5,
            "given_name": "Mohammed",
            "family_name": "Harris",
            "email": "yrosenbaum@example.org",
            "email_verified_at": "2023-09-13T00:51:02.000000Z",
            "role": "owner",
            "telephone": "341.691.4638",
            "country_id": 2,
            "city": "Santiago",
            "street": null,
            "number": "744",
            "appartment": "1",
            "zip_code": "9888",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:02.000000Z",
            "updated_at": "2023-09-13T00:51:02.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    },
    {
        "id": 4,
        "title": "Itaque id vero dicta odio aut pariatur.",
        "description": "Similique optio et iusto placeat quaerat. Quam libero odit id dolore animi. Consequatur dolores quaerat harum repellat. Perferendis saepe debitis quos et.",
        "price": "21311.14",
        "bedrooms": 3,
        "bathrooms": 2,
        "area": 506,
        "location": "Boston",
        "phoneNumber": "(979) 263-3325",
        "propertyType": "House",
        "propertyAddress": "3866 Hoppe Center\nNorth Ilamouth, NC 42096-3499",
        "propertyDescription": "Ducimus quia aut sit quod dolores iste doloribus. Dolorum ea consequatur aut et natus ut omnis. Iure quae perferendis voluptatum iure sint praesentium. Dolorem error quisquam est eum aut et.",
        "rentalPrice": null,
        "leaseTerm": "12 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "543.00",
        "rentalAgreement": "Qui vel nemo accusamus porro ea id. Commodi modi rem eos non id natus. Dignissimos dolor velit nemo aliquam facere voluptatum animi cupiditate.",
        "preferredTenantProfile": "Adipisci rerum doloribus est ut qui. Quia quasi modi rerum vel. Reiciendis et rerum consequuntur perferendis nam.",
        "additionalNote": "Officiis debitis laboriosam iste incidunt officia molestias. Omnis ut rerum itaque dolorum. Numquam veritatis blanditiis atque quam sint atque. Minima harum fugiat veniam suscipit deserunt expedita. Odio nesciunt ut animi eos saepe voluptatem aut.",
        "owner": {
            "id": 7,
            "given_name": "Remington",
            "family_name": "Leffler",
            "email": "brandon48@example.com",
            "email_verified_at": "2023-09-13T00:51:02.000000Z",
            "role": "owner",
            "telephone": "+1-843-605-9137",
            "country_id": 5,
            "city": "Paris",
            "street": null,
            "number": "110",
            "appartment": "245",
            "zip_code": "7109",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:02.000000Z",
            "updated_at": "2023-09-13T00:51:02.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    },
    {
        "id": 5,
        "title": "Odio repellat provident modi voluptatem laudantium distinctio.",
        "description": "Dolore sed rem doloribus esse quisquam velit. Doloremque dicta est ut sed occaecati voluptatem. Quia incidunt nesciunt qui quibusdam a beatae cum.",
        "price": "86777.77",
        "bedrooms": 2,
        "bathrooms": 3,
        "area": 2989,
        "location": "Boston",
        "phoneNumber": "(669) 698-8814",
        "propertyType": "Apartment",
        "propertyAddress": "688 Theresia Keys Suite 777\nNew Carlottaside, AZ 02340",
        "propertyDescription": "Exercitationem mollitia et minus qui expedita non molestiae fuga. Minima sit laborum itaque dolores voluptas consequatur placeat. Maiores rerum consectetur asperiores velit nemo omnis animi. Magni quia asperiores natus illum aliquam possimus.",
        "rentalPrice": null,
        "leaseTerm": "36 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "584.76",
        "rentalAgreement": "Architecto in sit dolor quo velit quia. Explicabo praesentium vel sapiente omnis maxime omnis optio. Rem eos eum aperiam modi dicta soluta.",
        "preferredTenantProfile": "Est qui culpa nihil nostrum iste cum doloremque nobis. Neque consequuntur sit autem quam itaque vel non. Nemo odit sint est totam rem nisi necessitatibus. Consequuntur tempora in id quo.",
        "additionalNote": "Deleniti cum ut aperiam veniam sint dolorem laboriosam. Dolore nesciunt quibusdam autem quas veniam modi. Voluptas eligendi officia omnis et autem et. Voluptatibus nobis dolorem consequatur vel. Est sequi non aut magni laboriosam aut odit.",
        "owner": {
            "id": 9,
            "given_name": "Amya",
            "family_name": "Willms",
            "email": "bednar.verla@example.net",
            "email_verified_at": "2023-09-13T00:51:02.000000Z",
            "role": "owner",
            "telephone": "(680) 334-3150",
            "country_id": 3,
            "city": "Paris",
            "street": null,
            "number": "664",
            "appartment": "5790772",
            "zip_code": "7980",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:02.000000Z",
            "updated_at": "2023-09-13T00:51:02.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    },
    {
        "id": 6,
        "title": "Vitae tenetur omnis possimus quia dolorem harum.",
        "description": "Harum non quia sed aut ut facere ipsam. Commodi aut minima modi qui iusto aspernatur accusamus.",
        "price": "2324.53",
        "bedrooms": 2,
        "bathrooms": 3,
        "area": 3911,
        "location": "Lima",
        "phoneNumber": "+16579129495",
        "propertyType": "Apartment",
        "propertyAddress": "2806 Bruen Stravenue Suite 207\nLake Edythe, NV 41447-9929",
        "propertyDescription": "Blanditiis velit sed occaecati facere dolores. Ullam temporibus ducimus est laboriosam. Nihil debitis est quasi cum assumenda. Exercitationem voluptatum quos sed eum molestias.",
        "rentalPrice": null,
        "leaseTerm": "24 Months",
        "negotiable": 0,
        "available": null,
        "rentPaymentMethod": "Credit Card",
        "securityDeposit": "983.76",
        "rentalAgreement": "Expedita voluptatem tempora quidem et quidem rem. Deserunt et beatae quia consequatur et. Voluptatem ut tempore non neque. Similique error recusandae iusto consequatur est.",
        "preferredTenantProfile": "Reiciendis illo praesentium recusandae eligendi libero. Autem dignissimos sed dolorem. Enim sed molestiae est labore ducimus. Dolore voluptatem qui qui dolore vel sit. Est sint voluptatem hic est.",
        "additionalNote": "Aliquam harum eaque distinctio voluptatibus. Aspernatur voluptatibus et officiis et. Omnis eius ad nobis dolores voluptatem ipsa quaerat possimus.",
        "owner": {
            "id": 11,
            "given_name": "Tabitha",
            "family_name": "Schamberger",
            "email": "deondre.brown@example.org",
            "email_verified_at": "2023-09-13T00:51:03.000000Z",
            "role": "owner",
            "telephone": "(828) 523-0426",
            "country_id": 2,
            "city": "Paris",
            "street": null,
            "number": "708",
            "appartment": "597574",
            "zip_code": "1058",
            "avatar": null,
            "is_verified": 0,
            "created_at": "2023-09-13T00:51:03.000000Z",
            "updated_at": "2023-09-13T00:51:03.000000Z"
        },
        "tenant": null,
        "status": "Unlisted",
        "dateRegistered": "2023-09-13",
        "dateUpdated": "2023-09-13"
    }
]

export const ContextProvider = ({children}) => {
    const [currentUser, setCurrentUser] = useState({
        name: 'Johnny Bravo',
        email: 'johnnyb@gmail.com',
        imgUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80'
    })
    const [userToken, setUserToken] = useState('133')
    const [properties, setProperties] = useState(propertiesJson)

    return (
        <StateContext.Provider value={{ 
            currentUser,
            setCurrentUser,
            userToken,
            setUserToken,
            properties,
            setProperties
         }}>
            {children}
        </StateContext.Provider>
    )
}

export const useStateContext = () => useContext(StateContext)